Default: &defaults
  user: greek
  password: greek
  host: localhost
  port: 5432
  database: greek
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: greek-snap_test
  <<: *defaults

Staging:
  database: greek-snap_staging
  poolsize: 100
  <<: *defaults

Production:
  database: greek-snap_production
  poolsize: 100
  <<: *defaults
